-- Generated by `go test ./store -update-schema` — DO NOT EDIT.
--
-- Flattened snapshot of the squirrel index schema at version 19, for humans
-- and agents who want the current shape without replaying the migration
-- chain in migrations.go. It is NOT used to create or migrate databases —
-- a fresh DB is built by applyV5 plus the migration registry. The golden
-- test TestSchemaSnapshot fails if this file drifts from that chain.

CREATE TABLE contents (
			id             INTEGER PRIMARY KEY,
			blake3         BLOB NOT NULL UNIQUE CHECK (length(blake3) = 32),
			size_bytes     INTEGER NOT NULL,
			origin_node_id INTEGER REFERENCES nodes(id),
			origin_run_id  INTEGER
		);

CREATE INDEX idx_contents_origin_node ON contents(origin_node_id)
		 WHERE origin_node_id IS NOT NULL;

CREATE TABLE destination_run_ids (
			volume_id      INTEGER NOT NULL REFERENCES volumes(id),
			destination    TEXT NOT NULL,
			origin_node_id INTEGER NOT NULL REFERENCES nodes(id),
			origin_run_id  INTEGER NOT NULL,
			updated_at_ns  INTEGER NOT NULL, verify_method TEXT,
			PRIMARY KEY (volume_id, destination, origin_node_id)
		);

CREATE TABLE destination_run_ids_history (
			id             INTEGER PRIMARY KEY,
			volume_id      INTEGER NOT NULL,
			destination    TEXT NOT NULL,
			origin_node_id INTEGER NOT NULL,
			origin_run_id  INTEGER NOT NULL,
			at_ns          INTEGER NOT NULL
		, verify_method TEXT);

CREATE INDEX idx_destination_run_ids_history
		 ON destination_run_ids_history(volume_id, destination);

CREATE TABLE "files" (
			folder_id         INTEGER NOT NULL REFERENCES folders(id),
			name              TEXT NOT NULL,
			content_id        INTEGER NOT NULL REFERENCES contents(id),
			mtime_ns          INTEGER NOT NULL,
			status            TEXT NOT NULL CHECK (status IN ('present','missing','superseded','offloaded')),
			first_seen_run_id INTEGER NOT NULL REFERENCES runs(id),
			last_seen_run_id  INTEGER NOT NULL REFERENCES runs(id),
			indexed_at_ns     INTEGER NOT NULL, status_changed_run_id INTEGER REFERENCES runs(id),
			PRIMARY KEY (folder_id, name, content_id)
		);

CREATE INDEX idx_files_content ON files(content_id);

CREATE INDEX idx_files_missing ON files(folder_id, name) WHERE status = 'missing';

CREATE UNIQUE INDEX uniq_files_live_per_path ON files(folder_id, name) WHERE status != 'superseded';

CREATE TABLE folders (
			id                  INTEGER PRIMARY KEY,
			volume_id           INTEGER NOT NULL REFERENCES volumes(id),
			parent_id           INTEGER REFERENCES folders(id),
			path                TEXT NOT NULL,
			shallow_blake3      BLOB CHECK (shallow_blake3 IS NULL OR length(shallow_blake3) = 32),
			deep_blake3         BLOB CHECK (deep_blake3    IS NULL OR length(deep_blake3)    = 32),
			last_changed_run_id INTEGER REFERENCES runs(id), file_count      INTEGER NOT NULL DEFAULT 0, cumulative_size INTEGER NOT NULL DEFAULT 0,
			UNIQUE (volume_id, path)
		);

CREATE INDEX idx_folders_parent ON folders(parent_id);

CREATE TABLE hook_runs (
			id                INTEGER PRIMARY KEY,
			volume_id         INTEGER NOT NULL REFERENCES volumes(id),
			trigger           TEXT NOT NULL CHECK (trigger IN ('change','interval')),
			triggering_run_id INTEGER REFERENCES runs(id),
			changed           INTEGER NOT NULL CHECK (changed IN (0, 1)),
			started_at_ns     INTEGER NOT NULL,
			ended_at_ns       INTEGER,
			status            TEXT NOT NULL CHECK (status IN ('running','success','failed')),
			exit_code         INTEGER,
			error             TEXT,
			CHECK (
				(trigger = 'change'   AND triggering_run_id IS NOT NULL) OR
				(trigger = 'interval' AND triggering_run_id IS NULL)
			)
		);

CREATE INDEX idx_hook_runs_volume_trigger ON hook_runs(volume_id, trigger, started_at_ns);

CREATE TABLE nodes (
			id                     INTEGER PRIMARY KEY,
			name                   TEXT NOT NULL UNIQUE,
			endpoint               TEXT,
			public_key_fingerprint TEXT
		);

CREATE TABLE peer_sync_state (
			volume_id          INTEGER NOT NULL REFERENCES volumes(id),
			peer_node_id       INTEGER NOT NULL REFERENCES nodes(id),
			last_shared_run_id INTEGER,
			last_synced_at     INTEGER NOT NULL,
			PRIMARY KEY (volume_id, peer_node_id)
		);

CREATE TABLE peer_sync_state_history (
			id                 INTEGER PRIMARY KEY,
			volume_id          INTEGER NOT NULL REFERENCES volumes(id),
			peer_node_id       INTEGER NOT NULL REFERENCES nodes(id),
			last_shared_run_id INTEGER,
			last_synced_at     INTEGER NOT NULL,
			at_ns              INTEGER NOT NULL
		);

CREATE INDEX idx_peer_sync_history_pair
		 ON peer_sync_state_history(volume_id, peer_node_id);

CREATE TABLE "remote_objects" (
			content_id      INTEGER NOT NULL REFERENCES contents(id),
			destination     TEXT NOT NULL,
			uploaded_run_id INTEGER NOT NULL REFERENCES runs(id),
			checksum_algo   TEXT,
			checksum        TEXT,
			verified_at_ns  INTEGER,
			PRIMARY KEY (content_id, destination),
			CHECK ((checksum_algo IS NULL) = (checksum IS NULL))
		);

CREATE TABLE "runs" (
			id            INTEGER PRIMARY KEY,
			kind          TEXT NOT NULL CHECK (kind IN ('index','sync','restore','audit','offload')),
			volume_id     INTEGER REFERENCES volumes(id),
			destination   TEXT,
			started_at_ns INTEGER NOT NULL,
			ended_at_ns   INTEGER,
			status        TEXT NOT NULL CHECK (status IN ('running','success','failed','partial')),
			error         TEXT,
			file_count    INTEGER NOT NULL DEFAULT 0,
			peer_node_id      INTEGER REFERENCES nodes(id),
			correlated_run_id INTEGER,
			shallow INTEGER CHECK (shallow IS NULL OR shallow IN (0, 1)),
			CHECK (
				(kind IN ('index','audit','offload') AND destination IS NULL) OR
				(kind IN ('sync','restore') AND destination IS NOT NULL AND destination != '')
			)
		);

CREATE INDEX idx_runs_destination ON runs(destination) WHERE destination IS NOT NULL;

CREATE INDEX idx_runs_volume_started ON runs(volume_id, started_at_ns);

CREATE TABLE runs_audit (
			id         INTEGER PRIMARY KEY,
			run_id     INTEGER NOT NULL REFERENCES runs(id),
			transition TEXT NOT NULL,
			operator   TEXT,
			at_ns      INTEGER NOT NULL,
			note       TEXT
		);

CREATE INDEX idx_runs_audit_run ON runs_audit(run_id);

CREATE TABLE schema_version (version INTEGER NOT NULL PRIMARY KEY);

CREATE TABLE volumes (
			id   INTEGER PRIMARY KEY,
			name TEXT NOT NULL UNIQUE,
			path TEXT NOT NULL
		);

