package store

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
)

// schemaSnapshotNodeName is the self-node identity seeded into the
// throwaway in-memory database canonicalSchemaSQL migrates. It never
// reaches the dumped DDL (the nodes row is data, not schema), so any
// nodeNameRE-valid string works; a fixed one keeps generation
// deterministic.
const schemaSnapshotNodeName = "schema-snapshot"

// schemaSnapshotHeader prefixes the generated store/schema.sql. The %d is
// filled with SchemaVersion. It states plainly that the file is generated
// and how to refresh it, so a human or agent who opens it isn't tempted to
// hand-edit a file the golden test will overwrite.
const schemaSnapshotHeader = "-- Generated by `go test ./store -update-schema` — DO NOT EDIT.\n" +
	"--\n" +
	"-- Flattened snapshot of the squirrel index schema at version %d, for humans\n" +
	"-- and agents who want the current shape without replaying the migration\n" +
	"-- chain in migrations.go. It is NOT used to create or migrate databases —\n" +
	"-- a fresh DB is built by applyV5 plus the migration registry. The golden\n" +
	"-- test TestSchemaSnapshot fails if this file drifts from that chain.\n"

// DumpSchema returns the DDL currently materialised in the database as a
// deterministic SQL script: every CREATE statement recorded in
// sqlite_master (tables, indexes, triggers), grouped by table and ordered
// so the output is stable across runs. Indexes SQLite generates implicitly
// for PRIMARY KEY / UNIQUE constraints are omitted — they carry a NULL sql
// and are already implied by their table's CREATE. The CLI's `db schema`
// subcommand prints this for whichever database it opens.
func (s *Store) DumpSchema(ctx context.Context) (string, error) {
	return dumpSchema(ctx, s.db)
}

func dumpSchema(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT sql FROM sqlite_master
		WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'
		ORDER BY tbl_name,
			CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 WHEN 'trigger' THEN 2 ELSE 3 END,
			name`)
	if err != nil {
		return "", fmt.Errorf("read sqlite_master: %w", err)
	}
	defer rows.Close()

	var b strings.Builder
	for rows.Next() {
		var stmt string
		if err := rows.Scan(&stmt); err != nil {
			return "", fmt.Errorf("scan schema row: %w", err)
		}
		b.WriteString(strings.TrimSpace(stmt))
		b.WriteString(";\n\n")
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("iterate schema rows: %w", err)
	}
	return b.String(), nil
}

// canonicalSchemaSQL migrates a throwaway in-memory database to
// SchemaVersion through the same chain Open uses, then returns the snapshot
// (header + DDL) that store/schema.sql must match. It is the single source
// of truth shared by the golden test and its -update-schema rewrite path.
//
// The in-memory DB is opened via buildDSN so it carries the same pragmas
// (foreign_keys, _txlock, …) a production Open applies — the snapshot is
// generated under the same constraints real databases migrate under.
func canonicalSchemaSQL(ctx context.Context) (string, error) {
	db, err := openSQLite(buildDSN(":memory:"))
	if err != nil {
		return "", err
	}
	defer db.Close()

	s := &Store{db: db} // empty path → migrate skips the pre-migration backup
	if err := s.migrate(ctx, schemaSnapshotNodeName, OpenOptions{DisablePreMigrationBackup: true}); err != nil {
		return "", fmt.Errorf("migrate in-memory schema: %w", err)
	}
	body, err := s.DumpSchema(ctx)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf(schemaSnapshotHeader, SchemaVersion) + "\n" + body, nil
}
