-- Generated by `go test ./store -update-schema` — DO NOT EDIT.
--
-- Flattened snapshot of the squirrel index schema at version 13, for humans
-- and agents who want the current shape without replaying the migration
-- chain in migrations.go. It is NOT used to create or migrate databases —
-- a fresh DB is built by applyV5 plus the migration registry. The golden
-- test TestSchemaSnapshot fails if this file drifts from that chain.

CREATE TABLE "files" (
		folder_id         INTEGER NOT NULL REFERENCES folders(id),
		name              TEXT NOT NULL,
		blake3            BLOB NOT NULL CHECK (length(blake3) = 32),
		size_bytes        INTEGER NOT NULL,
		mtime_ns          INTEGER NOT NULL,
		status            TEXT NOT NULL CHECK (status IN ('present','missing','superseded')),
		first_seen_run_id INTEGER NOT NULL REFERENCES runs(id),
		last_seen_run_id  INTEGER NOT NULL REFERENCES runs(id),
		indexed_at_ns     INTEGER NOT NULL,
		source_node_id    INTEGER REFERENCES nodes(id),
		source_run_id     INTEGER REFERENCES runs(id),
		PRIMARY KEY (folder_id, name, blake3)
	);

CREATE INDEX idx_files_blake3 ON files(blake3, folder_id, name);

CREATE INDEX idx_files_missing ON files(folder_id, name) WHERE status = 'missing';

CREATE INDEX idx_files_source_node ON files(source_node_id)
		 WHERE status = 'present' AND source_node_id IS NOT NULL;

CREATE UNIQUE INDEX uniq_files_live_per_path ON files(folder_id, name) WHERE status != 'superseded';

CREATE TRIGGER files_blake3_immutable BEFORE UPDATE OF blake3 ON files
		 BEGIN
		     SELECT RAISE(ABORT, 'blake3 is immutable; supersede the row and insert a new one');
		 END;

CREATE TABLE folders (
			id                  INTEGER PRIMARY KEY,
			volume_id           INTEGER NOT NULL REFERENCES volumes(id),
			parent_id           INTEGER REFERENCES folders(id),
			path                TEXT NOT NULL,
			shallow_blake3      BLOB CHECK (shallow_blake3 IS NULL OR length(shallow_blake3) = 32),
			deep_blake3         BLOB CHECK (deep_blake3    IS NULL OR length(deep_blake3)    = 32),
			last_changed_run_id INTEGER REFERENCES runs(id), file_count      INTEGER NOT NULL DEFAULT 0, cumulative_size INTEGER NOT NULL DEFAULT 0,
			UNIQUE (volume_id, path)
		);

CREATE INDEX idx_folders_parent ON folders(parent_id);

CREATE TABLE hook_runs (
			id                INTEGER PRIMARY KEY,
			volume_id         INTEGER NOT NULL REFERENCES volumes(id),
			trigger           TEXT NOT NULL CHECK (trigger IN ('change','interval')),
			triggering_run_id INTEGER REFERENCES runs(id),
			changed           INTEGER NOT NULL CHECK (changed IN (0, 1)),
			started_at_ns     INTEGER NOT NULL,
			ended_at_ns       INTEGER,
			status            TEXT NOT NULL CHECK (status IN ('running','success','failed')),
			exit_code         INTEGER,
			error             TEXT,
			CHECK (
				(trigger = 'change'   AND triggering_run_id IS NOT NULL) OR
				(trigger = 'interval' AND triggering_run_id IS NULL)
			)
		);

CREATE INDEX idx_hook_runs_volume_trigger ON hook_runs(volume_id, trigger, started_at_ns);

CREATE TABLE nodes (
			id                     INTEGER PRIMARY KEY,
			name                   TEXT NOT NULL UNIQUE,
			endpoint               TEXT,
			public_key_fingerprint TEXT
		);

CREATE TABLE peer_sync_state (
			volume_id          INTEGER NOT NULL REFERENCES volumes(id),
			peer_node_id       INTEGER NOT NULL REFERENCES nodes(id),
			last_shared_run_id INTEGER,
			last_synced_at     INTEGER NOT NULL,
			PRIMARY KEY (volume_id, peer_node_id)
		);

CREATE TABLE peer_sync_state_history (
			id                 INTEGER PRIMARY KEY,
			volume_id          INTEGER NOT NULL REFERENCES volumes(id),
			peer_node_id       INTEGER NOT NULL REFERENCES nodes(id),
			last_shared_run_id INTEGER,
			last_synced_at     INTEGER NOT NULL,
			at_ns              INTEGER NOT NULL
		);

CREATE INDEX idx_peer_sync_history_pair
		 ON peer_sync_state_history(volume_id, peer_node_id);

CREATE TABLE "runs" (
			id            INTEGER PRIMARY KEY,
			kind          TEXT NOT NULL CHECK (kind IN ('index','sync','restore','audit')),
			volume_id     INTEGER REFERENCES volumes(id),
			destination   TEXT,
			started_at_ns INTEGER NOT NULL,
			ended_at_ns   INTEGER,
			status        TEXT NOT NULL CHECK (status IN ('running','success','failed','partial')),
			error         TEXT,
			file_count    INTEGER NOT NULL DEFAULT 0,
			peer_node_id      INTEGER REFERENCES nodes(id),
			correlated_run_id INTEGER, shallow INTEGER CHECK (shallow IS NULL OR shallow IN (0, 1)),
			CHECK (
				(kind IN ('index','audit') AND destination IS NULL) OR
				(kind IN ('sync','restore') AND destination IS NOT NULL AND destination != '')
			)
		);

CREATE INDEX idx_runs_destination ON runs(destination) WHERE destination IS NOT NULL;

CREATE INDEX idx_runs_volume_started ON runs(volume_id, started_at_ns);

CREATE TABLE runs_audit (
			id         INTEGER PRIMARY KEY,
			run_id     INTEGER NOT NULL REFERENCES runs(id),
			transition TEXT NOT NULL,
			operator   TEXT,
			at_ns      INTEGER NOT NULL,
			note       TEXT
		);

CREATE INDEX idx_runs_audit_run ON runs_audit(run_id);

CREATE TABLE schema_version (version INTEGER NOT NULL PRIMARY KEY);

CREATE TABLE volumes (
			id   INTEGER PRIMARY KEY,
			name TEXT NOT NULL UNIQUE,
			path TEXT NOT NULL
		);

